//
//  VELKeyPressEventRecognizer.h
//  Velvet
//
//  Created by Justin Spahr-Summers on 06.03.12.
//  Copyright (c) 2012 Bitswift. All rights reserved.
//

#import <Velvet/VELEventRecognizer.h>

/**
 * A discrete event recognizer that identifies presses of one or more keys.
 *
 * This recognizer will not recognize key events that are generated by holding
 * down a single key (i.e., key repeat).
 */
@interface VELKeyPressEventRecognizer : VELEventRecognizer

/**
 * @name Configuring Recognition
 */

/**
 * An array of <VELKeyPress> objects that represent the key presses that the
 * receiver should recognize.
 *
 * Key presses must be recognized in the same order they appear in the array.
 */
@property (nonatomic, copy) NSArray *keyPressesToRecognize;

/**
 * The maximum amount of time that may pass between two key presses.
 *
 * If this time limit is exceeded, the recognizer will fail.
 */
@property (nonatomic, assign) NSTimeInterval maximumKeyPressInterval;

@end
